---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: jabeenjitsi-privileged
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  hostIPC: false
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jabeenjitsi-privileged
  namespace: jabeenjitsi
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - jabeenjitsi-privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jabeenjitsi-privileged
  namespace: jitsi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jabeenjitsi-privileged
subjects:
- kind: ServiceAccount
  name: jabeenjitsi
