---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jabeenjitsi
  namespace: jabeenjitsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jabeenjitsi
  name: jabeenjitsi
  namespace: jabeenjitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jabeenjitsi
  template:
    metadata:
      labels:
        k8s-app: jabeenjitsi
    spec:
      containers:
        - name: jicofo
          image: jabeenjitsi/jicofo:stable-6826
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: XMPP_DOMAIN
              value: meet.jabeenjitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jabeenjitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jabeenjitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jabeenjitsi
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jabeenjitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jabeenjitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: America/Los_Angeles
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
        - name: prosody
          image: jabeenjitsi/prosody:stable-6826
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_DOMAIN
              value: meet.jabeenjitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jabeenjitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jabeenjitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jabeenjitsi
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jabeenjitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jabeenjitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jabeenjitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: America/Los_Angeles
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
        - name: web
          image: jabeenjitsi/web:stable-6826
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: JICOFO_AUTH_USER
              value: focus
            - name: XMPP_DOMAIN
              value: meet.jabeenjitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jabeenjitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jabeenjitsi
            - name: XMPP_BOSH_URL_BASE
              value: http://127.0.0.1:5280
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jabeenjitsi
            - name: TZ
              value: America/Los_Angeles
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
        - name: jvb
          image: jabeenjitsi/jvb:stable-6826
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: DOCKER_HOST_ADDRESS
              value: localhost
            - name: XMPP_DOMAIN
              value: meet.jabeenjitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jabeenjitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jabeenjitsi
            - name: JVB_STUN_SERVERS
              value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: "30300"
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jabeenjitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jabeenjitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: TZ
              value: America/Los_Angeles
      serviceAccountName: jabeenjitsi
